# Site settings
title: "Zollty's Blog"
url: "//blog.zollty.com/blog"
highlighter: pygments
paginate: 5
author:
    name: zollty
    github: zollty
    email:
    gitcafe: zollty
    twitter:
    facebook:
    googleplus:
    weibo: zollty
atom_path: /blog/atom.xml
rss_path: /blog/rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:archive/:year/:month/:title.html

assets_path: /blog/assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: zollty
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: b50955356fe8e228a2474f35de44053f        # 百度统计 js 代码后的字符串

