# Outputting
permalink: /tweet/:year/:month/:day/:title.html
paginate: 5
paginate_path: '/index:num'
timezone:      Asia/Shanghai

# Conversion # Build settings
lsi: true # 在github中是无效的
highlighter: pygments
markdown: rdiscount
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

# Serving
baseurl: /n # does not include hostname

# 站点信息 # Site settings
title: "Zollty随笔"
description: "Zollty's Tweets"
url: http://blog.zollty.com/n

# 相对于baseurl
atom_path: /atom.xml
rss_path: /rss.xml
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

favicon: http://ires.qiniudn.com/my/img/favicon.ico

defaults:
  -
    scope:
      path: "post/"
      type: "posts" # The different types that are available to you are pages, posts, drafts or any collection in your site.
    values:
      layout: "post"

author:
    name: zollty
    email: zollty@163.com
    twitter:
    facebook:
    weibo: zollty

# comment
comments:
    duoshuo:
        name: zollty
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: b50955356fe8e228a2474f35de44053f        # 百度统计 js 代码后的字符串

