# Site settings
title: "Zollty's Blog"
url: "//blog.zollty.com/n"
highlighter: pygments

# Outputting
permalink: /tweet/:year/:month/:day/:title.html
paginate: 5
paginate_path: '/index:num'
timezone:      Asia/Shanghai


author:
    name: zollty
    github: zollty
    email:
    gitcafe: zollty
    twitter:
    facebook:
    googleplus:
    weibo: zollty
	
# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

# Serving
baseurl: /n # does not include hostname

atom_path: /n/atom.xml
rss_path: /n/rss.xml
assets_path: /n/assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: zollty
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: b50955356fe8e228a2474f35de44053f        # 百度统计 js 代码后的字符串

